export const requiredEnvs = [
  'REACT_APP_NODE_ENV',

  'REACT_APP_LISTEN_PORT',
  // 'REACT_APP_LOG_LEVEL',
  'REACT_APP_JWT_SECRET_KEY',
  'REACT_APP_JWT_ACCESS_EXP',
  'REACT_APP_JWT_REFRESH_EXP',

  'REACT_APP_CORS_ORIGINS',
  'REACT_APP_CORS_METHODS',
  'REACT_APP_CORS_HEADERS',
  'REACT_APP_CORS_CREDENTIALS',
  'REACT_APP_CORS_MAX_AGE',
  'DATABASE_URL',
  'PGSSLROOTCERT'
]